# Generated by Django 5.0 on 2024-01-29 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskAssignDate',
            new_name='AssignDate',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskDescription',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskTitle',
            new_name='Title',
        ),
    ]
