# Generated by Django 5.0 on 2024-01-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=200)),
                ('phoenNo', models.CharField(max_length=11)),
                ('instrument_type', models.CharField(max_length=50)),
            ],
        ),
    ]
